[viewer_users]
Guest = "Guest2026"
guest_2 = "Shipping2026"

[viewer_user_companies]
Guest = "interglobo"
guest_2 = "shipping_service"

[viewer_company_names]
interglobo = "Interglobo"
shipping_service = "Shipping Service"
